// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Data.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config {

  /// <summary>Holder for reflection information generated from Data.proto</summary>
  public static partial class DataReflection {

    #region Descriptor
    /// <summary>File descriptor for Data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpEYXRhLnByb3RvKlIKCWNhc3RfdHlwZRISCg5jYXN0X3R5cGVfbm9uZRAA",
            "EhgKFGNhc3RfdHlwZV9pbml0aWF0aXZlEAESFwoTY2FzdF90eXBlX3Bhc3Np",
            "dml0eRACKm8KC2VmZmVjdF90eXBlEhQKEGVmZmVjdF90eXBlX25vbmUQABIc",
            "ChhlZmZlY3RfdHlwZV9nZW5lcmFsX2hhcm0QARIUChBlZmZlY3RfdHlwZV9o",
            "YXJtEAISFgoSZWZmZWN0X3R5cGVfZWZmZWN0EAMq0hMKEGl0ZW1fZGV0YWls",
            "X3R5cGUSGQoVaXRlbV9kZXRhaWxfdHlwZV9ub25lEAASHAoXaXRlbV9kZXRh",
            "aWxfdHlwZV9tYXhfaHAQkU4SHAoXaXRlbV9kZXRhaWxfdHlwZV9jdXJfaHAQ",
            "kk4SHAoXaXRlbV9kZXRhaWxfdHlwZV9hdHRhY2sQk04SIgodaXRlbV9kZXRh",
            "aWxfdHlwZV9hdHRhY2tfc3BlZWQQlE4SJQogaXRlbV9kZXRhaWxfdHlwZV9h",
            "dHRhY2tfZGlzdGFuY2UQlU4SIgodaXRlbV9kZXRhaWxfdHlwZV9hdHRhY2tf",
            "cmFuZ2UQlk4SIgodaXRlbV9kZXRhaWxfdHlwZV9hdHRhY2tfYW5nbGUQl04S",
            "IgodaXRlbV9kZXRhaWxfdHlwZV9yZWxvYWRfc3BlZWQQmE4SGgoVaXRlbV9k",
            "ZXRhaWxfdHlwZV9jbGlwEJlOEh8KGml0ZW1fZGV0YWlsX3R5cGVfY3JpdF9y",
            "YXRlEJpOEiAKG2l0ZW1fZGV0YWlsX3R5cGVfY3JpdF9kYW1nZRCbThIeChlp",
            "dGVtX2RldGFpbF90eXBlX2hpdF9yYXRlEJxOEhwKF2l0ZW1fZGV0YWlsX3R5",
            "cGVfcGllcmNlEJ1OEhwKF2l0ZW1fZGV0YWlsX3R5cGVfZGVmZW5kEJ5OEhwK",
            "F2l0ZW1fZGV0YWlsX3R5cGVfd2lsZnVsEJ9OEiYKIWl0ZW1fZGV0YWlsX3R5",
            "cGVfZGFtYWdlX3JlZHVjdGlvbhCgThIaChVpdGVtX2RldGFpbF90eXBlX2Rv",
            "Z2UQoU4SIAobaXRlbV9kZXRhaWxfdHlwZV9tb3ZlX3NwZWVkEKJOEhwKF2l0",
            "ZW1fZGV0YWlsX3R5cGVfc3Ryb25nEKNOEh4KGWl0ZW1fZGV0YWlsX3R5cGVf",
            "cGh5c2lxdWUQpE4SGQoUaXRlbV9kZXRhaWxfdHlwZV9hZ2wQpU4SGQoUaXRl",
            "bV9kZXRhaWxfdHlwZV9pbnQQpk4SGwoWaXRlbV9kZXRhaWxfdHlwZV9sdWNr",
            "eRCnThIdChhpdGVtX2RldGFpbF90eXBlX2V4cGxvZGUQqE4SGwoWaXRlbV9k",
            "ZXRhaWxfdHlwZV90cmVhdBCpThIkCh9pdGVtX2RldGFpbF90eXBlX21lbGVl",
            "X2hpdF90aW1lEKpOEh0KGGl0ZW1fZGV0YWlsX3R5cGVfZ3Jvd19ocBCrThIh",
            "ChxpdGVtX2RldGFpbF90eXBlX2dyb3dfYXR0YWNrEKxOEiEKHGl0ZW1fZGV0",
            "YWlsX3R5cGVfZ3Jvd19kZWZlbmQQrU4SHgoZaXRlbV9kZXRhaWxfdHlwZV9n",
            "cm93X2hpdBCuThIfChppdGVtX2RldGFpbF90eXBlX2dyb3dfZG9nZRCvThIh",
            "ChxpdGVtX2RldGFpbF90eXBlX2dyb3dfZXhwb2RlELBOEiAKG2l0ZW1fZGV0",
            "YWlsX3R5cGVfZ3Jvd190cmVhdBCxThIkCh9pdGVtX2RldGFpbF90eXBlX2dy",
            "b3dfY3JpdF9yYXRlELJOEiUKIGl0ZW1fZGV0YWlsX3R5cGVfZ3Jvd19jcml0",
            "X2RhbWdlELNOEiIKHWl0ZW1fZGV0YWlsX3R5cGVfYXR0YWNrX3RpbWVzELRO",
            "EiUKIGl0ZW1fZGV0YWlsX3R5cGVfYXR0YWNrX2ludGVydmFsELVOEiAKG2l0",
            "ZW1fZGV0YWlsX3R5cGVfdmlld19yYW5nZRC2ThIiCh1pdGVtX2RldGFpbF90",
            "eXBlX2Rhbmdlcl9yYW5nZRC3ThIgChtpdGVtX2RldGFpbF90eXBlX2RvZ2Vf",
            "cmFuZ2UQuE4SJAofaXRlbV9kZXRhaWxfdHlwZV9yb3RhdGlvbl9zcGVlZBC5",
            "ThIoCiNpdGVtX2RldGFpbF90eXBlX3dyZXN0bGVfdGVjaG5vbG9neRD5VRIk",
            "Ch9pdGVtX2RldGFpbF90eXBlX2d1bl90ZWNobm9sb2d5EPpVEigKI2l0ZW1f",
            "ZGV0YWlsX3R5cGVfZXhwbG9kZV90ZWNobm9sb2d5EPtVEiYKIWl0ZW1fZGV0",
            "YWlsX3R5cGVfdHJlYXRfdGVjaG5vbG9neRD8VRIlCiBpdGVtX2RldGFpbF90",
            "eXBlX2Nvb2tfdGVjaG5vbG9neRDhXRImCiFpdGVtX2RldGFpbF90eXBlX3By",
            "b2JlX3RlY2hub2xvZ3kQ4l0SKgolaXRlbV9kZXRhaWxfdHlwZV9tYWNoaW5p",
            "bmdfdGVjaG5vbG9neRDjXRIpCiRpdGVtX2RldGFpbF90eXBlX2VsZWN0cm9u",
            "X3RlY2hub2xvZ3kQ5F0SJwoiaXRlbV9kZXRhaWxfdHlwZV9tZWRpY2FfdGVj",
            "aG5vbG9neRDlXRIpCiRpdGVtX2RldGFpbF90eXBlX2NoZW1pY2FsX3RlY2hu",
            "b2xvZ3kQ5l0SJwoiaXRlbV9kZXRhaWxfdHlwZV9zZXdpbmdfdGVjaG5vbG9n",
            "eRDnXRIqCiVpdGVtX2RldGFpbF90eXBlX21lY2hhbmlzbV90ZWNobm9sb2d5",
            "EOhdEiEKHGl0ZW1fZGV0YWlsX3R5cGVfZmlnaHRfbGV2ZWwQ6V0SHQoYaXRl",
            "bV9kZXRhaWxfdHlwZV9zYXRpZXR5EMllEhoKFWl0ZW1fZGV0YWlsX3R5cGVf",
            "Y2VsbBDKZRIdChhpdGVtX2RldGFpbF90eXBlX2RpYW1vbmQQy2USGgoVaXRl",
            "bV9kZXRhaWxfdHlwZV9mdWVsEMxlEigKI2l0ZW1fZGV0YWlsX3R5cGVfZXF1",
            "aXBtZW50X2NhcGFjaXR5ELFtEigKI2l0ZW1fZGV0YWlsX3R5cGVfd2FyZWhv",
            "dXNlX2NhcGFjaXR5ELJtEiYKIWl0ZW1fZGV0YWlsX3R5cGVfY29ja3BpdF9j",
            "YXBhY2l0eRCzbRIkCh9pdGVtX2RldGFpbF90eXBlX2hvcnNlcG93ZXJfbWF4",
            "ELRtEigKI2l0ZW1fZGV0YWlsX3R5cGVfZnVlbF90YW5rX2NhcGFjaXR5ELVt",
            "EiIKHWl0ZW1fZGV0YWlsX3R5cGVfcG93ZXJfc3VwcGx5ELZtEikKJGl0ZW1f",
            "ZGV0YWlsX3R5cGVfd2FyZWhvdXNlX2NhcGFjaXR5MhC3bRIpCiRpdGVtX2Rl",
            "dGFpbF90eXBlX3dhcmVob3VzZV9jYXBhY2l0eTMQuG0SKQokaXRlbV9kZXRh",
            "aWxfdHlwZV93YXJlaG91c2VfY2FwYWNpdHk0ELltEikKJGl0ZW1fZGV0YWls",
            "X3R5cGVfd2FyZWhvdXNlX2NhcGFjaXR5NRC6bRIpCiRpdGVtX2RldGFpbF90",
            "eXBlX3dhcmVob3VzZV9jYXBhY2l0eTYQu20qNgoEcmFjZRINCglyYWNlX25v",
            "bmUQABIOCgpyYWNlX2h1bWFuEAESDwoLcmFjZV96b21iaWUQAiqAAgoSdGFy",
            "Z2V0X3NlbGVjdF90eXBlEhsKF3RhcmdldF9zZWxlY3RfdHlwZV9ub25lEAAS",
            "HgoadGFyZ2V0X3NlbGVjdF90eXBlX25lYXJlc3QQARIfCht0YXJnZXRfc2Vs",
            "ZWN0X3R5cGVfZmFydGhlc3QQAhIfCht0YXJnZXRfc2VsZWN0X3R5cGVfaHBf",
            "bGVhc3QQAxIhCh10YXJnZXRfc2VsZWN0X3R5cGVfaHBfbWF4aW11bRAEEikK",
            "JXRhcmdldF9zZWxlY3RfdHlwZV9iYXR0bGVfYWJpbGl0eV9tYXgQBRIdChl0",
            "YXJnZXRfc2VsZWN0X3R5cGVfcmFuZG9tEAZCCaoCBkNvbmZpZ2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Config.cast_type), typeof(global::Config.effect_type), typeof(global::Config.item_detail_type), typeof(global::Config.race), typeof(global::Config.target_select_type), }, null));
    }
    #endregion

  }
  #region Enums
  public enum cast_type {
    /// <summary>
    /// 无
    /// </summary>
    [pbr::OriginalName("cast_type_none")] None = 0,
    /// <summary>
    /// 主动
    /// </summary>
    [pbr::OriginalName("cast_type_initiative")] Initiative = 1,
    /// <summary>
    /// 被动
    /// </summary>
    [pbr::OriginalName("cast_type_passivity")] Passivity = 2,
  }

  public enum effect_type {
    /// <summary>
    /// 无
    /// </summary>
    [pbr::OriginalName("effect_type_none")] None = 0,
    /// <summary>
    /// 普通伤害
    /// </summary>
    [pbr::OriginalName("effect_type_general_harm")] GeneralHarm = 1,
    /// <summary>
    /// 爆炸伤害
    /// </summary>
    [pbr::OriginalName("effect_type_harm")] Harm = 2,
    /// <summary>
    /// 治疗效果
    /// </summary>
    [pbr::OriginalName("effect_type_effect")] Effect = 3,
  }

  public enum item_detail_type {
    /// <summary>
    /// 无
    /// </summary>
    [pbr::OriginalName("item_detail_type_none")] None = 0,
    /// <summary>
    /// 最大生命值
    /// </summary>
    [pbr::OriginalName("item_detail_type_max_hp")] MaxHp = 10001,
    /// <summary>
    /// 当前生命值
    /// </summary>
    [pbr::OriginalName("item_detail_type_cur_hp")] CurHp = 10002,
    /// <summary>
    /// 攻击力
    /// </summary>
    [pbr::OriginalName("item_detail_type_attack")] Attack = 10003,
    /// <summary>
    /// 攻击速度
    /// </summary>
    [pbr::OriginalName("item_detail_type_attack_speed")] AttackSpeed = 10004,
    /// <summary>
    /// 攻击距离
    /// </summary>
    [pbr::OriginalName("item_detail_type_attack_distance")] AttackDistance = 10005,
    /// <summary>
    /// 攻击范围
    /// </summary>
    [pbr::OriginalName("item_detail_type_attack_range")] AttackRange = 10006,
    /// <summary>
    /// 攻击角度
    /// </summary>
    [pbr::OriginalName("item_detail_type_attack_angle")] AttackAngle = 10007,
    /// <summary>
    /// 换弹速度
    /// </summary>
    [pbr::OriginalName("item_detail_type_reload_speed")] ReloadSpeed = 10008,
    /// <summary>
    /// 弹夹容量
    /// </summary>
    [pbr::OriginalName("item_detail_type_clip")] Clip = 10009,
    /// <summary>
    /// 暴击率
    /// </summary>
    [pbr::OriginalName("item_detail_type_crit_rate")] CritRate = 10010,
    /// <summary>
    /// 暴击伤害
    /// </summary>
    [pbr::OriginalName("item_detail_type_crit_damge")] CritDamge = 10011,
    /// <summary>
    /// 命中率
    /// </summary>
    [pbr::OriginalName("item_detail_type_hit_rate")] HitRate = 10012,
    /// <summary>
    /// 穿透性
    /// </summary>
    [pbr::OriginalName("item_detail_type_pierce")] Pierce = 10013,
    /// <summary>
    /// 防御力
    /// </summary>
    [pbr::OriginalName("item_detail_type_defend")] Defend = 10014,
    /// <summary>
    /// 韧性
    /// </summary>
    [pbr::OriginalName("item_detail_type_wilful")] Wilful = 10015,
    /// <summary>
    /// 伤害减免
    /// </summary>
    [pbr::OriginalName("item_detail_type_damage_reduction")] DamageReduction = 10016,
    /// <summary>
    /// 闪躲
    /// </summary>
    [pbr::OriginalName("item_detail_type_doge")] Doge = 10017,
    /// <summary>
    /// 移动速度
    /// </summary>
    [pbr::OriginalName("item_detail_type_move_speed")] MoveSpeed = 10018,
    /// <summary>
    /// 强壮
    /// </summary>
    [pbr::OriginalName("item_detail_type_strong")] Strong = 10019,
    /// <summary>
    /// 体质
    /// </summary>
    [pbr::OriginalName("item_detail_type_physique")] Physique = 10020,
    /// <summary>
    /// 敏捷
    /// </summary>
    [pbr::OriginalName("item_detail_type_agl")] Agl = 10021,
    /// <summary>
    /// 智力
    /// </summary>
    [pbr::OriginalName("item_detail_type_int")] Int = 10022,
    /// <summary>
    /// 幸运
    /// </summary>
    [pbr::OriginalName("item_detail_type_lucky")] Lucky = 10023,
    /// <summary>
    /// 爆炸效果
    /// </summary>
    [pbr::OriginalName("item_detail_type_explode")] Explode = 10024,
    /// <summary>
    /// 医疗效果
    /// </summary>
    [pbr::OriginalName("item_detail_type_treat")] Treat = 10025,
    /// <summary>
    /// 近战命中判定时间
    /// </summary>
    [pbr::OriginalName("item_detail_type_melee_hit_time")] MeleeHitTime = 10026,
    /// <summary>
    /// 等级成长生命值
    /// </summary>
    [pbr::OriginalName("item_detail_type_grow_hp")] GrowHp = 10027,
    /// <summary>
    /// 等级成长攻击力
    /// </summary>
    [pbr::OriginalName("item_detail_type_grow_attack")] GrowAttack = 10028,
    /// <summary>
    /// 等级成长防御力
    /// </summary>
    [pbr::OriginalName("item_detail_type_grow_defend")] GrowDefend = 10029,
    /// <summary>
    /// 等级成长命中率
    /// </summary>
    [pbr::OriginalName("item_detail_type_grow_hit")] GrowHit = 10030,
    /// <summary>
    /// 等级成长躲闪
    /// </summary>
    [pbr::OriginalName("item_detail_type_grow_doge")] GrowDoge = 10031,
    /// <summary>
    /// 等级成长爆炸伤害
    /// </summary>
    [pbr::OriginalName("item_detail_type_grow_expode")] GrowExpode = 10032,
    /// <summary>
    /// 等级成长医疗效果
    /// </summary>
    [pbr::OriginalName("item_detail_type_grow_treat")] GrowTreat = 10033,
    /// <summary>
    /// 等级成长暴击率
    /// </summary>
    [pbr::OriginalName("item_detail_type_grow_crit_rate")] GrowCritRate = 10034,
    /// <summary>
    /// 等级成长暴击伤害
    /// </summary>
    [pbr::OriginalName("item_detail_type_grow_crit_damge")] GrowCritDamge = 10035,
    /// <summary>
    /// 攻击次数
    /// </summary>
    [pbr::OriginalName("item_detail_type_attack_times")] AttackTimes = 10036,
    /// <summary>
    /// 攻击间隔
    /// </summary>
    [pbr::OriginalName("item_detail_type_attack_interval")] AttackInterval = 10037,
    /// <summary>
    /// 视野范围
    /// </summary>
    [pbr::OriginalName("item_detail_type_view_range")] ViewRange = 10038,
    /// <summary>
    /// 威胁距离
    /// </summary>
    [pbr::OriginalName("item_detail_type_danger_range")] DangerRange = 10039,
    /// <summary>
    /// 躲避距离
    /// </summary>
    [pbr::OriginalName("item_detail_type_doge_range")] DogeRange = 10040,
    /// <summary>
    /// 转身速度
    /// </summary>
    [pbr::OriginalName("item_detail_type_rotation_speed")] RotationSpeed = 10041,
    /// <summary>
    /// 格斗
    /// </summary>
    [pbr::OriginalName("item_detail_type_wrestle_technology")] WrestleTechnology = 11001,
    /// <summary>
    /// 枪械
    /// </summary>
    [pbr::OriginalName("item_detail_type_gun_technology")] GunTechnology = 11002,
    /// <summary>
    /// 爆炸
    /// </summary>
    [pbr::OriginalName("item_detail_type_explode_technology")] ExplodeTechnology = 11003,
    /// <summary>
    /// 治疗
    /// </summary>
    [pbr::OriginalName("item_detail_type_treat_technology")] TreatTechnology = 11004,
    /// <summary>
    /// 烹饪
    /// </summary>
    [pbr::OriginalName("item_detail_type_cook_technology")] CookTechnology = 12001,
    /// <summary>
    /// 探索
    /// </summary>
    [pbr::OriginalName("item_detail_type_probe_technology")] ProbeTechnology = 12002,
    /// <summary>
    /// 加工
    /// </summary>
    [pbr::OriginalName("item_detail_type_machining_technology")] MachiningTechnology = 12003,
    /// <summary>
    /// 电子
    /// </summary>
    [pbr::OriginalName("item_detail_type_electron_technology")] ElectronTechnology = 12004,
    /// <summary>
    /// 医药
    /// </summary>
    [pbr::OriginalName("item_detail_type_medica_technology")] MedicaTechnology = 12005,
    /// <summary>
    /// 化工
    /// </summary>
    [pbr::OriginalName("item_detail_type_chemical_technology")] ChemicalTechnology = 12006,
    /// <summary>
    /// 缝纫
    /// </summary>
    [pbr::OriginalName("item_detail_type_sewing_technology")] SewingTechnology = 12007,
    /// <summary>
    /// 机械
    /// </summary>
    [pbr::OriginalName("item_detail_type_mechanism_technology")] MechanismTechnology = 12008,
    /// <summary>
    /// 战斗等级
    /// </summary>
    [pbr::OriginalName("item_detail_type_fight_level")] FightLevel = 12009,
    /// <summary>
    /// 饱食度
    /// </summary>
    [pbr::OriginalName("item_detail_type_satiety")] Satiety = 13001,
    /// <summary>
    /// 电池
    /// </summary>
    [pbr::OriginalName("item_detail_type_cell")] Cell = 13002,
    /// <summary>
    /// 钻石
    /// </summary>
    [pbr::OriginalName("item_detail_type_diamond")] Diamond = 13003,
    /// <summary>
    /// 燃料
    /// </summary>
    [pbr::OriginalName("item_detail_type_fuel")] Fuel = 13004,
    /// <summary>
    /// 设备容量
    /// </summary>
    [pbr::OriginalName("item_detail_type_equipment_capacity")] EquipmentCapacity = 14001,
    /// <summary>
    /// 仓库容量
    /// </summary>
    [pbr::OriginalName("item_detail_type_warehouse_capacity")] WarehouseCapacity = 14002,
    /// <summary>
    /// 座舱容量
    /// </summary>
    [pbr::OriginalName("item_detail_type_cockpit_capacity")] CockpitCapacity = 14003,
    /// <summary>
    /// 最大马力
    /// </summary>
    [pbr::OriginalName("item_detail_type_horsepower_max")] HorsepowerMax = 14004,
    /// <summary>
    /// 油箱容量
    /// </summary>
    [pbr::OriginalName("item_detail_type_fuel_tank_capacity")] FuelTankCapacity = 14005,
    /// <summary>
    /// 提供电力
    /// </summary>
    [pbr::OriginalName("item_detail_type_power_supply")] PowerSupply = 14006,
    /// <summary>
    /// 仓库2容量
    /// </summary>
    [pbr::OriginalName("item_detail_type_warehouse_capacity2")] WarehouseCapacity2 = 14007,
    /// <summary>
    /// 仓库3容量
    /// </summary>
    [pbr::OriginalName("item_detail_type_warehouse_capacity3")] WarehouseCapacity3 = 14008,
    /// <summary>
    /// 仓库4容量
    /// </summary>
    [pbr::OriginalName("item_detail_type_warehouse_capacity4")] WarehouseCapacity4 = 14009,
    /// <summary>
    /// 仓库5容量
    /// </summary>
    [pbr::OriginalName("item_detail_type_warehouse_capacity5")] WarehouseCapacity5 = 14010,
    /// <summary>
    /// 仓库6容量
    /// </summary>
    [pbr::OriginalName("item_detail_type_warehouse_capacity6")] WarehouseCapacity6 = 14011,
  }

  public enum race {
    /// <summary>
    /// 无
    /// </summary>
    [pbr::OriginalName("race_none")] None = 0,
    /// <summary>
    /// 人类
    /// </summary>
    [pbr::OriginalName("race_human")] Human = 1,
    /// <summary>
    /// 僵尸
    /// </summary>
    [pbr::OriginalName("race_zombie")] Zombie = 2,
  }

  public enum target_select_type {
    /// <summary>
    /// 无
    /// </summary>
    [pbr::OriginalName("target_select_type_none")] None = 0,
    /// <summary>
    /// 最近
    /// </summary>
    [pbr::OriginalName("target_select_type_nearest")] Nearest = 1,
    /// <summary>
    /// 最远
    /// </summary>
    [pbr::OriginalName("target_select_type_farthest")] Farthest = 2,
    /// <summary>
    /// 最低血量
    /// </summary>
    [pbr::OriginalName("target_select_type_hp_least")] HpLeast = 3,
    /// <summary>
    /// 最高血量
    /// </summary>
    [pbr::OriginalName("target_select_type_hp_maximum")] HpMaximum = 4,
    /// <summary>
    /// 最高战力
    /// </summary>
    [pbr::OriginalName("target_select_type_battle_ability_max")] BattleAbilityMax = 5,
    /// <summary>
    /// 随机
    /// </summary>
    [pbr::OriginalName("target_select_type_random")] Random = 6,
  }

  #endregion

}

#endregion Designer generated code
