# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Data.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\nData.proto\"j\n\nHeroPrefab\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x11\n\tModelPath\x18\x02 \x01(\t\x12\x11\n\tModelName\x18\x03 \x01(\t\x12\x0e\n\x06Melees\x18\x04 \x03(\x05\x12\x0f\n\x07\x41\x62ility\x18\x05 \x03(\x05\x12\t\n\x01\x41\x18\x06 \x01(\x05\"\x9f\x01\n\nDataHelper\x12\x13\n\x0bmessageType\x18\x01 \x03(\t\x12\x38\n\x0fHeroPrefab_dict\x18\x02 \x03(\x0b\x32\x1f.DataHelper.HeroPrefabDictEntry\x1a\x42\n\x13HeroPrefabDictEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.HeroPrefab:\x02\x38\x01\x42\t\xaa\x02\x06\x43onfigb\x06proto3')
)




_HEROPREFAB = _descriptor.Descriptor(
  name='HeroPrefab',
  full_name='HeroPrefab',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='HeroPrefab.ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ModelPath', full_name='HeroPrefab.ModelPath', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ModelName', full_name='HeroPrefab.ModelName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Melees', full_name='HeroPrefab.Melees', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Ability', full_name='HeroPrefab.Ability', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='A', full_name='HeroPrefab.A', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=120,
)


_DATAHELPER_HEROPREFABDICTENTRY = _descriptor.Descriptor(
  name='HeroPrefabDictEntry',
  full_name='DataHelper.HeroPrefabDictEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DataHelper.HeroPrefabDictEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='DataHelper.HeroPrefabDictEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=282,
)

_DATAHELPER = _descriptor.Descriptor(
  name='DataHelper',
  full_name='DataHelper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageType', full_name='DataHelper.messageType', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='HeroPrefab_dict', full_name='DataHelper.HeroPrefab_dict', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DATAHELPER_HEROPREFABDICTENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=282,
)

_DATAHELPER_HEROPREFABDICTENTRY.fields_by_name['value'].message_type = _HEROPREFAB
_DATAHELPER_HEROPREFABDICTENTRY.containing_type = _DATAHELPER
_DATAHELPER.fields_by_name['HeroPrefab_dict'].message_type = _DATAHELPER_HEROPREFABDICTENTRY
DESCRIPTOR.message_types_by_name['HeroPrefab'] = _HEROPREFAB
DESCRIPTOR.message_types_by_name['DataHelper'] = _DATAHELPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HeroPrefab = _reflection.GeneratedProtocolMessageType('HeroPrefab', (_message.Message,), dict(
  DESCRIPTOR = _HEROPREFAB,
  __module__ = 'Data_pb2'
  # @@protoc_insertion_point(class_scope:HeroPrefab)
  ))
_sym_db.RegisterMessage(HeroPrefab)

DataHelper = _reflection.GeneratedProtocolMessageType('DataHelper', (_message.Message,), dict(

  HeroPrefabDictEntry = _reflection.GeneratedProtocolMessageType('HeroPrefabDictEntry', (_message.Message,), dict(
    DESCRIPTOR = _DATAHELPER_HEROPREFABDICTENTRY,
    __module__ = 'Data_pb2'
    # @@protoc_insertion_point(class_scope:DataHelper.HeroPrefabDictEntry)
    ))
  ,
  DESCRIPTOR = _DATAHELPER,
  __module__ = 'Data_pb2'
  # @@protoc_insertion_point(class_scope:DataHelper)
  ))
_sym_db.RegisterMessage(DataHelper)
_sym_db.RegisterMessage(DataHelper.HeroPrefabDictEntry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\006Config'))
_DATAHELPER_HEROPREFABDICTENTRY.has_options = True
_DATAHELPER_HEROPREFABDICTENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
