# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Data.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\nData.proto\"\x92\x01\n\x08Timeline\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x10\n\x08\x44uration\x18\x02 \x01(\x05\x12\x13\n\x0bRecoverTime\x18\x03 \x01(\x05\x12\x15\n\rPreInputStart\x18\x04 \x01(\x05\x12\x13\n\x0bPreInputEnd\x18\x05 \x01(\x05\x12\x15\n\rAnimationMove\x18\x06 \x03(\x05\x12\x10\n\x08HitTimes\x18\x07 \x03(\x05\"\x97\x01\n\nDataHelper\x12\x13\n\x0bmessageType\x18\x01 \x03(\t\x12\x34\n\rTimeline_dict\x18\x02 \x03(\x0b\x32\x1d.DataHelper.TimelineDictEntry\x1a>\n\x11TimelineDictEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x18\n\x05value\x18\x02 \x01(\x0b\x32\t.Timeline:\x02\x38\x01\x42\t\xaa\x02\x06\x43onfigb\x06proto3')
)




_TIMELINE = _descriptor.Descriptor(
  name='Timeline',
  full_name='Timeline',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='Timeline.ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Duration', full_name='Timeline.Duration', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RecoverTime', full_name='Timeline.RecoverTime', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PreInputStart', full_name='Timeline.PreInputStart', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PreInputEnd', full_name='Timeline.PreInputEnd', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AnimationMove', full_name='Timeline.AnimationMove', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='HitTimes', full_name='Timeline.HitTimes', index=6,
      number=7, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=161,
)


_DATAHELPER_TIMELINEDICTENTRY = _descriptor.Descriptor(
  name='TimelineDictEntry',
  full_name='DataHelper.TimelineDictEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DataHelper.TimelineDictEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='DataHelper.TimelineDictEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=315,
)

_DATAHELPER = _descriptor.Descriptor(
  name='DataHelper',
  full_name='DataHelper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageType', full_name='DataHelper.messageType', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Timeline_dict', full_name='DataHelper.Timeline_dict', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DATAHELPER_TIMELINEDICTENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=315,
)

_DATAHELPER_TIMELINEDICTENTRY.fields_by_name['value'].message_type = _TIMELINE
_DATAHELPER_TIMELINEDICTENTRY.containing_type = _DATAHELPER
_DATAHELPER.fields_by_name['Timeline_dict'].message_type = _DATAHELPER_TIMELINEDICTENTRY
DESCRIPTOR.message_types_by_name['Timeline'] = _TIMELINE
DESCRIPTOR.message_types_by_name['DataHelper'] = _DATAHELPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Timeline = _reflection.GeneratedProtocolMessageType('Timeline', (_message.Message,), dict(
  DESCRIPTOR = _TIMELINE,
  __module__ = 'Data_pb2'
  # @@protoc_insertion_point(class_scope:Timeline)
  ))
_sym_db.RegisterMessage(Timeline)

DataHelper = _reflection.GeneratedProtocolMessageType('DataHelper', (_message.Message,), dict(

  TimelineDictEntry = _reflection.GeneratedProtocolMessageType('TimelineDictEntry', (_message.Message,), dict(
    DESCRIPTOR = _DATAHELPER_TIMELINEDICTENTRY,
    __module__ = 'Data_pb2'
    # @@protoc_insertion_point(class_scope:DataHelper.TimelineDictEntry)
    ))
  ,
  DESCRIPTOR = _DATAHELPER,
  __module__ = 'Data_pb2'
  # @@protoc_insertion_point(class_scope:DataHelper)
  ))
_sym_db.RegisterMessage(DataHelper)
_sym_db.RegisterMessage(DataHelper.TimelineDictEntry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\006Config'))
_DATAHELPER_TIMELINEDICTENTRY.has_options = True
_DATAHELPER_TIMELINEDICTENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
