# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Data.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\nData.proto\"\xf8\x01\n\ttask_main\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63hapter\x18\x02 \x01(\x05\x12\x11\n\ttask_type\x18\x03 \x01(\x05\x12\x0f\n\x07name_cn\x18\x04 \x01(\t\x12\x10\n\x08name_key\x18\x05 \x01(\t\x12\x13\n\x0b\x63hapter_des\x18\x06 \x01(\x05\x12\x0e\n\x06\x64\x65s_cn\x18\x07 \x01(\t\x12\x0f\n\x07\x64\x65s_key\x18\x08 \x01(\t\x12\"\n\tgoal_type\x18\t \x01(\x0e\x32\x0f.task_goal_type\x12\x0f\n\x07goal_id\x18\n \x01(\x05\x12\x10\n\x08goal_num\x18\x0b \x01(\x05\x12\x0b\n\x03\x62ox\x18\x0c \x01(\x05\x12\x0e\n\x06\x64ialog\x18\r \x03(\x05\"0\n\nDataHelper\x12\"\n\x0etask_main_list\x18\x01 \x03(\x0b\x32\n.task_main*\xf9\x01\n\x0etask_goal_type\x12\x17\n\x13task_goal_type_none\x10\x00\x12\x18\n\x14task_goal_type_build\x10\x01\x12\x19\n\x15task_goal_type_recipe\x10\x02\x12\x1b\n\x17task_goal_type_haveitem\x10\x03\x12\x1c\n\x18task_goal_type_challenge\x10\x04\x12\x1a\n\x16task_goal_type_relieve\x10\x05\x12 \n\x1ctask_goal_type_finishedother\x10\x06\x12 \n\x1ctask_goal_type_stayovernight\x10\x07\x42\t\xaa\x02\x06\x43onfigb\x06proto3')
)

_TASK_GOAL_TYPE = _descriptor.EnumDescriptor(
  name='task_goal_type',
  full_name='task_goal_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='task_goal_type_none', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='task_goal_type_build', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='task_goal_type_recipe', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='task_goal_type_haveitem', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='task_goal_type_challenge', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='task_goal_type_relieve', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='task_goal_type_finishedother', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='task_goal_type_stayovernight', index=7, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=316,
  serialized_end=565,
)
_sym_db.RegisterEnumDescriptor(_TASK_GOAL_TYPE)

task_goal_type = enum_type_wrapper.EnumTypeWrapper(_TASK_GOAL_TYPE)
task_goal_type_none = 0
task_goal_type_build = 1
task_goal_type_recipe = 2
task_goal_type_haveitem = 3
task_goal_type_challenge = 4
task_goal_type_relieve = 5
task_goal_type_finishedother = 6
task_goal_type_stayovernight = 7



_TASK_MAIN = _descriptor.Descriptor(
  name='task_main',
  full_name='task_main',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='task_main.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chapter', full_name='task_main.chapter', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_type', full_name='task_main.task_type', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name_cn', full_name='task_main.name_cn', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name_key', full_name='task_main.name_key', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chapter_des', full_name='task_main.chapter_des', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='des_cn', full_name='task_main.des_cn', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='des_key', full_name='task_main.des_key', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='goal_type', full_name='task_main.goal_type', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='goal_id', full_name='task_main.goal_id', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='goal_num', full_name='task_main.goal_num', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='box', full_name='task_main.box', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dialog', full_name='task_main.dialog', index=12,
      number=13, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=263,
)


_DATAHELPER = _descriptor.Descriptor(
  name='DataHelper',
  full_name='DataHelper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_main_list', full_name='DataHelper.task_main_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=313,
)

_TASK_MAIN.fields_by_name['goal_type'].enum_type = _TASK_GOAL_TYPE
_DATAHELPER.fields_by_name['task_main_list'].message_type = _TASK_MAIN
DESCRIPTOR.message_types_by_name['task_main'] = _TASK_MAIN
DESCRIPTOR.message_types_by_name['DataHelper'] = _DATAHELPER
DESCRIPTOR.enum_types_by_name['task_goal_type'] = _TASK_GOAL_TYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

task_main = _reflection.GeneratedProtocolMessageType('task_main', (_message.Message,), dict(
  DESCRIPTOR = _TASK_MAIN,
  __module__ = 'Data_pb2'
  # @@protoc_insertion_point(class_scope:task_main)
  ))
_sym_db.RegisterMessage(task_main)

DataHelper = _reflection.GeneratedProtocolMessageType('DataHelper', (_message.Message,), dict(
  DESCRIPTOR = _DATAHELPER,
  __module__ = 'Data_pb2'
  # @@protoc_insertion_point(class_scope:DataHelper)
  ))
_sym_db.RegisterMessage(DataHelper)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\006Config'))
# @@protoc_insertion_point(module_scope)
