# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Temp/Config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Temp/Config.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\006Config'),
  serialized_pb=_b('\n\x11Temp/Config.proto\"\x18\n\x08_2DArray\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x05\"\xad\x02\n\x0c\x43onfigHelper\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x11\n\tLONG_TEST\x18\x02 \x01(\x03\x12\x12\n\nFLOAT_TEST\x18\x03 \x01(\x02\x12\x11\n\tBOOL_TEST\x18\x04 \x01(\x08\x12\x10\n\x08STR_TEST\x18\x05 \x01(\t\x12\x12\n\nARRAY_TEST\x18\x06 \x03(\x05\x12\x16\n\x0e\x41RRAY_INT_TEST\x18\x07 \x03(\x05\x12:\n\x10MAP_INT_INT_TEST\x18\x08 \x03(\x0b\x32 .ConfigHelper.MAPINTINTTESTEntry\x12\'\n\x14\x41RRAY_ARRAY_INT_TEST\x18\t \x03(\x0b\x32\t._2DArray\x1a\x34\n\x12MAPINTINTTESTEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x42\t\xaa\x02\x06\x43onfigb\x06proto3')
)




__2DARRAY = _descriptor.Descriptor(
  name='_2DArray',
  full_name='_2DArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='_2DArray.data', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=45,
)


_CONFIGHELPER_MAPINTINTTESTENTRY = _descriptor.Descriptor(
  name='MAPINTINTTESTEntry',
  full_name='ConfigHelper.MAPINTINTTESTEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ConfigHelper.MAPINTINTTESTEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ConfigHelper.MAPINTINTTESTEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=349,
)

_CONFIGHELPER = _descriptor.Descriptor(
  name='ConfigHelper',
  full_name='ConfigHelper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='ConfigHelper.ID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='LONG_TEST', full_name='ConfigHelper.LONG_TEST', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='FLOAT_TEST', full_name='ConfigHelper.FLOAT_TEST', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='BOOL_TEST', full_name='ConfigHelper.BOOL_TEST', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='STR_TEST', full_name='ConfigHelper.STR_TEST', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ARRAY_TEST', full_name='ConfigHelper.ARRAY_TEST', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ARRAY_INT_TEST', full_name='ConfigHelper.ARRAY_INT_TEST', index=6,
      number=7, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MAP_INT_INT_TEST', full_name='ConfigHelper.MAP_INT_INT_TEST', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ARRAY_ARRAY_INT_TEST', full_name='ConfigHelper.ARRAY_ARRAY_INT_TEST', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CONFIGHELPER_MAPINTINTTESTENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=349,
)

_CONFIGHELPER_MAPINTINTTESTENTRY.containing_type = _CONFIGHELPER
_CONFIGHELPER.fields_by_name['MAP_INT_INT_TEST'].message_type = _CONFIGHELPER_MAPINTINTTESTENTRY
_CONFIGHELPER.fields_by_name['ARRAY_ARRAY_INT_TEST'].message_type = __2DARRAY
DESCRIPTOR.message_types_by_name['_2DArray'] = __2DARRAY
DESCRIPTOR.message_types_by_name['ConfigHelper'] = _CONFIGHELPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_2DArray = _reflection.GeneratedProtocolMessageType('_2DArray', (_message.Message,), {
  'DESCRIPTOR' : __2DARRAY,
  '__module__' : 'Temp.Config_pb2'
  # @@protoc_insertion_point(class_scope:_2DArray)
  })
_sym_db.RegisterMessage(_2DArray)

ConfigHelper = _reflection.GeneratedProtocolMessageType('ConfigHelper', (_message.Message,), {

  'MAPINTINTTESTEntry' : _reflection.GeneratedProtocolMessageType('MAPINTINTTESTEntry', (_message.Message,), {
    'DESCRIPTOR' : _CONFIGHELPER_MAPINTINTTESTENTRY,
    '__module__' : 'Temp.Config_pb2'
    # @@protoc_insertion_point(class_scope:ConfigHelper.MAPINTINTTESTEntry)
    })
  ,
  'DESCRIPTOR' : _CONFIGHELPER,
  '__module__' : 'Temp.Config_pb2'
  # @@protoc_insertion_point(class_scope:ConfigHelper)
  })
_sym_db.RegisterMessage(ConfigHelper)
_sym_db.RegisterMessage(ConfigHelper.MAPINTINTTESTEntry)


DESCRIPTOR._options = None
_CONFIGHELPER_MAPINTINTTESTENTRY._options = None
# @@protoc_insertion_point(module_scope)
